version: '3.8'
services:
  mysqldb:
    image: mysql:5.6
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: swordhealth
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080