version: '3.8'
services:
  mysqldb:
    image: mysql:5.6
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: swordhealth
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: "mysql"
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
  # app:
  #   container_name: swordhealth
  #   restart: always
  #   build: .
  #   ports:
  #     - 3333:3333
  #   environment:
  #     DB_HOST: mysqldb
  #     DB_PORT: 3306
  #     DB_USERNAME: "root"
  #     DB_PASSWORD: "mysql"
  #     DB_DATABASE: "swordhealth"
  #   links:
  #     - mysqldb
  